import { StyleSheet } from "react-native";
import { height,totalSize,width } from "react-native-dimension";
import { colors } from "../../services";
export const styles = StyleSheet.create({
    container:{
        height:height(14.6),
        borderTopLeftRadius:20,
        borderTopRightRadius:20,
        elevation:2,
        alignSelf:'center',
        width:width(100)
    },
    img:{
        width:width(22),
        height:height(12),
         resizeMode:'contain'
    },
    sub:{
        width:width(90),
        height:height(7.3),
        alignSelf:'center',
    },
    titlewrapper:{
        height:height(7.3),
        width:width(92),
    },
    headertitletext:{
        fontSize:totalSize(1.7),
        fontWeight:'700'
    },
    icon:{
        left:width(.77),
    },img:{
        width:width(22),
        height:height(12),
         resizeMode:'contain'
    },
    head:{
        width:width(91),
        height:height(7.3),
    },
    main:{
        borderBottomWidth:.25,
        borderColor:'gray',
        backgroundColor:colors.appBgColor1,
       width:width(100)
    },
    cartcontainer:{
        marginLeft:width(3.3)
    },
    htext:{
        color:colors.appTextColor6,
        fontWeight:'800',
        fontSize:totalSize(1.66),
        marginLeft:width(3.5) 
    },
    righticons:{
        width:width(20)
    },
    authhead:{
        width:width(92),
        height:height(7.3),
        alignSelf:'center',
        
    },
    mainhead:{
        width:width(100),
        borderBottomWidth:1.1,
        borderColor:colors.appTextColor9,
        height:height(7.23),
        backgroundColor:colors.appBgColor1
    },Textwrapper:{
      width:width(75),
      alignItems:'center',
      justifyContent:'center',
    },
    Titilestyle:{
        color:colors.appTextColor6,
        fontSize:totalSize(1.66),
        fontWeight:'800'
    },
    uploadicon:{
        right:width(8.33)
    },
    icons:{
        
        width:width(33)
    },
    userimage:{
        flexDirection:'column',
        alignItems:'center',
        height:height(8)
    },
    chatthead:{
        width:width(100),
        borderBottomWidth:1.1,
        borderColor:colors.appTextColor9,
        height:height(9.44)}
})