import Home from './home'
import SearchItem from './searchitem'
// import CarT from './cart'
import ProductCart from './productcart'
import Information from './Information'
import Shipping from './shippping'
import Payment from './payment'
import ProductDetail from './productdetail'
import RecommendedProduct from './recommendedproduct'
import Shop from './shop'
import PrivacyPolicy from './privacypolicy'
import OrderComplete from './ordercomplete'
import Profile from './profile'
import ChatList from './chatlist'
import Chat from './chat'
import MyOrder from './myorder'
import OrderDetail from './orderdetail'
import TermOfService from './termofservice'
export { Home,OrderDetail,TermOfService,Chat,MyOrder,ChatList,Profile, Payment,OrderComplete,PrivacyPolicy, RecommendedProduct, ProductDetail, Shipping, Information, ProductCart, SearchItem, Shop }